version: '3.8'

services:
  spica:
    build:
      context: ..                      # NOCTUA ルートをビルドコンテキストに
      dockerfile: docker/Dockerfile    # Dockerfile の相対パス
    container_name: Spica            # コンテナ名
    shm_size: '2gb'

    env_file:
      - .env                           # DATASET_PATH を読み込む

    ports:
      - '50001:8889'  # Jupyter Notebook
      - '8098:8098'   # Visdom

    volumes:
      - ../:/workspace                  # NOCTUA 全体を /workspace にマウント
      #- ${DATASET_PATH}:/workspace/data # データセットを /workspace/DataSet にマウント
      #- ${DATASET_PATH}:/workspace/DataSet

    working_dir: /workspace
    command: bash -c "jupyter notebook --allow-root --ip=0.0.0.0 --port=50001"