version: '3.8'

services:
  spica:  # ← 小文字に変更
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        REQUIREMENTS_FILE: requirements-gpu.txt
    container_name: spica  # ← 小文字に変更
    shm_size: '2gb'
    env_file:
      - .env
    volumes:
      - ../:/workspace
      - ${DATASET_PATH}:/workspace/DataSet
    working_dir: /workspace
    command: bash -c "jupyter notebook --allow-root --ip=0.0.0.0 --port=50001"
    gpus: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ports:
      - "50001:50001"
